name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greating
        run: echo "Hello from actions"
      - name: Print greatingÏ
        run: echo "Bye actions"
      
